# Generated by Django 5.1.15 on 2026-09-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_water_rate_per_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='combined_into',
            field=models.ForeignKey(blank=True, help_text='The head unit of the combined space this unit is part of.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='combined_units', to='buildings.unit'),
        ),
    ]
