# Generated by Django 5.1.15 on 2026-09-07 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_water_rate_200'),
        ('expenses', '0009_farm_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(blank=True, help_text="Unit this expense applies to. Leave blank for a cost that covers the whole building. Setting a unit pins the building to that unit's building.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='buildings.unit'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['unit'], name='expenses_ex_unit_id_633ad0_idx'),
        ),
    ]
