# Generated by Django 5.1.15 on 2026-08-30 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_care_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='agreed_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Deposit agreed with this tenant, if it differs from the standard rule. Leave blank to use one month's rent (three if commercial).", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
