# Generated by Django 5.1.15 on 2026-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_rent_due_on_the_fifth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_billable',
            field=models.BooleanField(db_index=True, default=True, help_text='Untick for an occupancy that is not charged rent (e.g. a caretaker housed as part of their job). Excluded from the monthly rent run, the rent and arrears reminders, and monthly statements.'),
        ),
    ]
