# Generated by Django 5.1.15 on 2026-09-19 20:09

import apps.payments.models
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_backfill_maintenance_expense_unit'),
        ('payments', '0018_arrears_check_constraints'),
        ('tenants', '0007_tenant_is_billable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'payments_document_sequence',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=10)),
                ('paid_to', models.CharField(blank=True, help_text='Phone number or bank account the money went to.', max_length=100)),
                ('reference', models.CharField(blank=True, help_text='M-Pesa / bank reference of the outgoing payment.', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Refund to send'), ('sent', 'Refunded'), ('cancelled', 'Cancelled'), ('void', 'Void')], max_length=10)),
                ('sent_on', models.DateField(blank=True, help_text='Date the money actually left.', null=True)),
                ('unit_classification', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('BUSINESS', 'Business / Commercial')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_mode', models.CharField(default='owner_self', max_length=30)),
                ('sent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When it was cancelled or voided.', null=True)),
                ('close_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
                ('sent_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payments_refund',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TenantCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('credit_type', models.CharField(choices=[('credit_note', 'Credit Note'), ('account_credit', 'Account Credit')], max_length=20)),
                ('reason', models.CharField(choices=[('billing_correction', 'We charged too much'), ('rent_concession', 'Rent discount or concession'), ('tenant_paid_cost', 'Tenant paid for a repair or cost that was ours'), ('opening_credit', 'Credit owed from before the system')], max_length=30)),
                ('credit_date', models.DateField(help_text='Date the credit takes effect and posts to the ledger.')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='The credit before VAT — what the charge is reduced by.', max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='VAT credited back. Only when the corrected charge carried VAT.', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text="net_amount + vat_amount — what the tenant's balance goes down by.", max_digits=10)),
                ('description', models.CharField(help_text="Printed on the tenant's statement — written for the tenant.", max_length=200)),
                ('internal_notes', models.TextField(blank=True, help_text='Never shown to the tenant.')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('evidence', models.FileField(blank=True, upload_to=apps.payments.models.credit_evidence_path)),
                ('evidence_name', models.CharField(blank=True, max_length=255)),
                ('on_hold', models.BooleanField(default=False, help_text='Held credit is not applied to invoices automatically.')),
                ('amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, help_text='Refunded, or set aside for a refund still to be sent.', max_digits=10)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('void', 'Void')], default='issued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_mode', models.CharField(default='owner_self', help_text="How it was approved. 'owner_self' = sole owner, no second approver.", max_length=30)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_approved', to=settings.AUTH_USER_MODEL)),
                ('arrears', models.ForeignKey(blank=True, help_text="The month's rent this credit note corrects.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='payments.arrears')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_created', to=settings.AUTH_USER_MODEL)),
                ('expense_category', models.ForeignKey(blank=True, help_text="For a cost the tenant bore on the landlord's behalf.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_credits', to='expenses.expensecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='tenants.tenant')),
                ('utility_charge', models.ForeignKey(blank=True, help_text='The water/utility charge this credit note corrects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='payments.utilitycharge')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_tenant_credit',
                'ordering': ['-credit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RefundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payments.refund')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_lines', to='payments.tenantcredit')),
            ],
            options={
                'db_table': 'payments_refund_line',
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_on', models.DateField()),
                ('origin', models.CharField(choices=[('on_issue', 'Applied when the credit was added'), ('billing', 'Applied by the monthly billing run'), ('owner', 'Applied by the owner')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reverse_reason', models.CharField(blank=True, max_length=255)),
                ('arrears', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_applications', to='payments.arrears')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='payments.tenantcredit')),
            ],
            options={
                'db_table': 'payments_credit_application',
                'ordering': ['applied_on', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', 'status'], name='payments_re_tenant__99d75d_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), ('sent_on__isnull', False), _connector='OR'), name='refund_sent_has_date'),
        ),
        migrations.AddIndex(
            model_name='tenantcredit',
            index=models.Index(fields=['tenant', 'status'], name='payments_te_tenant__bbdcf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredit',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gt', 0)), name='credit_net_positive'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredit',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0)), name='credit_vat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(models.F('net_amount'), '+', models.F('vat_amount')))), name='credit_amount_is_net_plus_vat'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount_applied__gte', 0), ('amount_refunded__gte', 0)), name='credit_usage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', django.db.models.expressions.CombinedExpression(models.F('amount_applied'), '+', models.F('amount_refunded')))), name='credit_not_overused'),
        ),
        migrations.AddConstraint(
            model_name='refundline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_application_positive'),
        ),
    ]
